pid /tmp/nginx.pid;
worker_processes                auto; # it will be determinate automatically by the number of core

error_log /dev/stderr;

events {
  worker_connections          1024;
}


http {
  access_log /dev/stdout;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;

  server_tokens off;
  absolute_redirect           off;
  default_type                application/octet-stream;
  include                     /etc/nginx/mime.types;
  keepalive_timeout           3000;
  sendfile                    on;

  include /etc/nginx/conf.d/*.conf;
}