version: "3.4"

volumes:
  postgres-data:

services:
  frontend-usagers-built:
    build:
      context: packages/frontend-usagers
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - $PWD/packages/frontend-usagers:/app:delegated
      - $HOME/.ssh:/home/node/.ssh:ro
      - $HOME/.gitconfig:/home/node/.gitconfig:ro
      - $HOME/.npm:/home/node/.npm:delegated
    env_file:
      - ./.env
    environment:
      TZ: Europe/Paris
      DEBUG: info:vao*
    ports:
      - 8080:8080

  frontend-bo-built:
    build:
      context: packages/frontend-bo
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - $PWD/packages/frontend-bo:/app:delegated
      - $HOME/.ssh:/home/node/.ssh:ro
      - $HOME/.gitconfig:/home/node/.gitconfig:ro
      - $HOME/.npm:/home/node/.npm:delegated
    env_file:
      - ./.env
    environment:
      DEBUG: info:vao*
    ports:
      - 8081:8080

  migrations-built:
    build:
      context: packages/migrations
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - $PWD/packages/migrations:/app:delegated
      - $HOME/.ssh:/home/node/.ssh:ro
      - $HOME/.gitconfig:/home/node/.gitconfig:ro
      - $HOME/.npm:/home/node/.npm:delegated
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      DEBUG: "*info*"

  backend-built:
    build:
      context: packages/backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - $PWD/packages/backend:/app:delegated
      - $HOME/.ssh:/home/node/.ssh:ro
      - $HOME/.gitconfig:/home/node/.gitconfig:ro
      - $HOME/.npm:/home/node/.npm:delegated
    depends_on:
      postgres:
        condition: service_started
      migrations-built:
        condition: service_completed_successfully
    env_file:
      - ./.env
    environment:
      DEBUG: info:vao*
    ports:
      - 3010:3000

  postgres:
    image: postgres:15.1
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg/lancement.sh:/docker-entrypoint-initdb.d/lancement.sh
      - ./pg/scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"
      - "1025:1025"
