packages:
  - "packages/*"
minimumReleaseAge: 20000
catalog:
  "@eslint/eslintrc": "^3.3.1"
  "@eslint/js": "^9.39.1"
  "@gouvfr/dsfr": "^1.14.0"
  "@gouvminint/vue-dsfr": "^8.6.0"
  "@iconify/vue": "^4.3.0"
  "@nuxt/eslint-config": "1.9.0"
  "@nuxt/test-utils": "^3.23.0"
  "@pinia/nuxt": "~0.5.4"
  "@vue/test-utils": "^2.4.6"
  "@vueform/multiselect": "~2.6.7"
  dayjs: "^1.11.13"
  debug: "^4.3.4"
  eslint: "^9.39.1"
  eslint-config-prettier: "^10.1.8"
  jest: "^30.4.2"
  maplibre-gl: "4.7.1"
  nodemon: "^3.1.10"
  nuxt: "^3.21.6"
  nuxt-maplibre: "^1.2.0"
  ofetch: "^1.5.1"
  pinia: "~2.2.2"
  prettier: "^3.2.5"
  query-string: "^6.14.1"
  supertest: "^7.2.2"
  ts-jest: "^29.4.10"
  tsx: "^4.20.6"
  typescript: "^5.9.3"
  vee-validate: "~4.15.1"
  vite: "^7.0.0"
  vitest: "^3.2.4"
  vue: "^3.5.13"
  vue-tsc: "^3.2.2"
  yup: "~1.4.0"
