apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: api-entreprise
  namespace: vao
spec:
  encryptedData:
    API_ENTREPRISE_TOKEN: AgCS/ZJclzAel1pdfdPFoA8n9CSTNZOaxhKZ8ossUmXrqQEUsST5zdn80D8YT6Xh3U9lSEPtjO29unlQX+N8JxNXoK9GtHUNXVMSfcX4LeFstyKGccYHorlSjhte5et+auVTfV1VMIc+bFAzZxDY9wXczIO0Ta08fYlL6QG3Jjq3nClHN4BeGb92LDqKVGmCKQX8HLYzA+FGGlRIi2fYrS8BWQUZjrQqiVBFzPSI31KwsDdyf+SWYj5fb4+0gnFcDQqMWI0ob/ZpkBDaiGqh0hzwfwoj6yCvoxtxDZeVwQpXsv/xC4xO+GrXGLQfT+MGfPnsil5aBQVEaKWyZBNFJC/BN+46XJUD4a8C+Ubkz30rtdnEaBHWDmMDlG/ssgRjUg62PKnx9Cwf/g+u7e1/0VNAziatJvo1ZydevrHVjckjesHKVDtnNFUN2h9YUo/y0v0HJv7IAO90dtOLahsK9A0XAkLtkYuZJrmsdAMAJzUbkBP43sOOC4RYyVSCXMndpWPFkeJFiEtYZSqDk4Lu7bwnqRH3aAFwtfMujrW9FOh/e5LBy9InupE+5wQNzyEMsn5ia6tdACF9GBLiTLlTH6ekeM0vJv/OdWbWGoZSElDknsvKUiMbMnKqCKp5LUAuhbmDED9q37U1gc2L24ICswbgRs1iDvCL5d4/ZhLzubAOYWEaj4LAL5eHJS5gNvdLm9d4JetYYyqbDwl1vyDygND946j9QBn9QmKnnotV2D22Q3tpo6txoPkcFvnuPJ9fvg8DoN6eOaEu+OHPLKRVjQ3PpkxScOlbKIcTCj8Cy2+dtIT3FrbQi2SvZNrEt4VHRyO8YX1SKloEFShYeNXPkIj5/uBo8jKZeIBh7sX+gMwFCddo8bPsf+10dByH73Dwk0V236Wr5wsyQvXNH2WNh33Di8m0PTj8FeXCD5sIJoY9nT5eaNoj448/G+dma9bQtQKIR6Tn9oNovuw5bLgKk09yxQW6/xbd2ErgKG3+kArTz3DnMRCKTt3MPLOUG/uukMeDLu5VR1Nofa+ZCD79BaDCGkGBTskKSFCN7M4MH2H/PxaH6h+3N3ZIjPMa3/LKmLjshtmMIRFMpBMcQLo5F9GWXQK+CkFi0kwwIeU2SWGVwfAJ410CfaXSqkBd7hF8c4wmn+kAQzmVTTWtpNcfaWHWbAfo23lRK/KjU9mEsbxEZIwE6Y6EtPgPH/zWzDAHDHvjHq3xyNnYQm2vX4lA/nV14ula9oz2S7P6OVrkZHXMjA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: api-entreprise
    type: Opaque
