kind: ConfigMap
apiVersion: v1
metadata:
  name: cron
data:
  FRONTEND_USAGERS_URL: "https://vao.social.gouv.fr"
  FRONTEND_BO_URL: "https://admin-vao.social.gouv.fr"
  SENDER_EMAIL: "nepasrepondre@vao.social.gouv.fr"
  SENTRY_DSN: "https://69ef3c41b27e8a066982f8839e4ec886@sentry2.fabrique.social.gouv.fr/44"
  SENTRY_ENABLED: "true"
  SENTRY_ENVIRONMENT: production
  BACKEND_CRON_REQUEST_ACCOUNT2M_NOTIFY_CRON: "0 9 * * *"
  BACKEND_CRON_REQUEST_DS8J15J_NOTIFY_CRON: "0 22 * * *"
  BACKEND_CRON_REQUEST_DS8J15J_DEADLINE_REMIND: "15"
  BACKEND_CRON_UPDATE_STATUT_DS_CRON: "0 02 * * *"
  BACKEND_CRON_REQUEST_ACTIONS_BO_CRON: "0 8 * * 1"
  BACKEND_CRON_DISABLE_ACCOUNT_3M_CRON: "5 8 * * 1"
  BACKEND_CRON_SUPPRESSION_COMPTE_INACTIF_NOTIFY: "0 9 * * 1"
  BACKEND_CRON_SUPPRESSION_COMPTE_INACTIF: "0 9 * * 2"
