kind: ConfigMap
apiVersion: v1
metadata:
  name: matomo
  namespace: vao
data:
  FRONTEND_USAGERS_MATOMO_ENABLED: "true"
  FRONTEND_USAGERS_MATOMO_HOST: "https://matomo.fabrique.social.gouv.fr"
  FRONTEND_USAGERS_MATOMO_ID: "104"
  FRONTEND_BO_MATOMO_ENABLED: "true"
  FRONTEND_BO_MATOMO_HOST: "https://matomo.fabrique.social.gouv.fr"
  FRONTEND_BO_MATOMO_ID: "106"
