maildev: {}

jobs:
  runs:
    build-frontend-usagers:
      with:
        buildArgs:
          NUXT_PUBLIC_ENVIRONMENT: "development"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
        secrets:
          sentry_auth_token:
            secretName: www-secret
            secretKey: SENTRY_AUTH_TOKEN
    build-frontend-bo:
      with:
        buildArgs:
          NUXT_PUBLIC_ENVIRONMENT: "development"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
