global:
  s3SecretName: vao-dev-app-access-key

maildev: {}

backend:
  vars:
    S3_BUCKET_ROOT_DIR: review-branch/{{ .Values.global.branchSlug32  }}/files

jobs:
  runs:
    build-frontend-usagers:
      with:
        buildArgs:
          NUXT_PUBLIC_ENVIRONMENT: "development"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
    build-frontend-bo:
      with:
        buildArgs:
          NUXT_PUBLIC_ENVIRONMENT: "development"
          NUXT_PUBLIC_SENTRY_ENABLED: "true"
    build-migrations:
      env:
        - name: PG_VAO_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: pg-superuser
              key: user
        - name: PG_VAO_SUPERPASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-superuser
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: pg-superuser
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: pg-superuser
              key: port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: PGDATABASE
        - name: S3_BUCKET_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.s3SecretName}}"
              key: bucket_endpoint
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.s3SecretName}}"
              key: bucket_name
        - name: S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.s3SecretName}}"
              key: bucket_region  
        - name: S3_BUCKET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.s3SecretName}}"
              key: bucket_access_key  
        - name: S3_BUCKET_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{.Values.global.s3SecretName}}"
              key: bucket_secret_key
        - name: S3_BUCKET_ROOT_DIR
          value: review-branch/{{ .Values.global.branchSlug32  }}/files