apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: frontend-secret
spec:
  encryptedData:
    SENTRY_AUTH_TOKEN: AgArF3x/emGTjDPKuJuGkaQzqf7Iv8BJjZ0NmuaLyUMXUf44cYHqwQuzL5VyhEj0QtEfET5K5A/k96eae84Pxq2Z8qgCLa2j3Y9lYlaDgjjn7O8IMrm8kgIon9Sr81XA5KpS0wn2wcEFnqqzl7u9gFOClZWBmA+ENEtS0QK1KmPFiw8NF+AvbPrzV5pIbd8AOBXQRTYHP4h9Xjn9SyyJosHp2T1ka4IKLCiyY+hx/nYyWlGiLNcZXBjy43AVxZECHa8+AmIjt/kLhP5rxGwsulpQVDwcNjmxS8tvmsGfWmRz8scKjC957Udg0RqyB37O+tyufh7nNkbv9vrJqKAaeBSxJpOqWj1JouM6seqt4eW7ZoRYed5jmqmMrrDAXelF7d/LM2c4tk19QE7ztINsjaDvH9S7vE6QnQfMD/PLbiz43StE6/PpP2NDShDg25mdL42wfpzbVCLISEMIm3wHBXy6yR/9aJOV3GgJsS4ZrtYgrhTRsuxqGTx1UVFkf9hh/1Zp2LdNGjSrh0aq5vCXWl/cRJpbsmSw+C3SCMxLUWfgZNPbBvneYhaL1miOoteaWZatcI4l+fkRkvDo8+9JTAmuYCE1W7Y/wAlRApK1xTehX8HKiWQf1aZopOO3nRI3B2EcvWf8KFbyCnZ7FGYRQK0WdmPwqBA0pBMBsuvL7m9oyrV+7Dh35cBzoeXaBGOKuL276wLvOiqRgYyTvrrWCB196rSm+C/CkTMZp6skUqJPDJ73Cc7Hr5T7WNWSN5cc5d9lfouFffeSYiNv1Ikod94nsIpoECc0cVDKOjv3Hq680n8oP078W8uNBodGfz0+DOeytTYp98fIutO6AKQpIYYkiMAeDMhDeO1s/JQiM9xRnMOAF6SkYRQZYmSAcIzQ+fT7bwlqaJuDHddZzQkFJmbjxgYu2OjeTfGJM3oKhr6clKndAiTBNdHSQ5kVaQvfnw29OSk5cODB0ShTb94Fo/dHh8qedYjgzcA2yP4y2FmoZLo1FBowlFhoRo2xZEDmuAT/aAxz+Y6k
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: frontend-secret
    type: Opaque
