apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: maildev-basic-auth
spec:
  encryptedData:
    auth: AgAq0z/REDVsSnB79GE/WCzlSK/LS8uM2Tsp0wAIv0jwdiNTDdK07Udb3HFkNXHriosKuYW3+Qd0mE1nulPZxwmejw+3TWDQNFF8hXN7KlooS73gMVMlUbAQkfPYs8jPykvhxcshIHhLZBTWf5glfUejdZbzrpp09+FVp41/H7IZpL1Co0BcNcufWwWNRp/oNnxOrk2CHJ0qzl6aqOH3nz95TfREl/ZjFmgUSoaThPAWp4xTNBeLY8DQ5t67NHgUlbNO4BAei3lE3yR4YrU0HvPWoQDVRnzNB4n7lDn9R9dCpDqpKn+sQKxpez9i7zYtYkG9/iuABYxhRiagtNui4MdN3ND/U+sS7iX4WSmzChlR8DE87P+4zbeRvNudg2SZhTeEGBYOQNtkeMwKTMZqIz3m7mSvkwq6CGsbv7X9jooGwNhML0wVuqgaS7j53hz9zE9YtDJHdNVuy0gKx+qzCGryw7mFh9bYViMlXJw7oBWPEPfOB/CAwpGjzRRokply2eKiu1e7xd0ZvItDhwvnv2xJy/SeFuM9tD7H3dd+2Y/wfCyxK8n69akTT9LAmTVW1vFdWC29RCimYQS1TCzpVichegsLxNmGQ+RDXzT44/XLasBb5FsvsjTBrzO+E9kXcghCAOB8oNgLJhnj57kaBKQzvWnganpc47FdMkC7TrHyaegUoZQayxZGHG4vvyaYiQZtwgi+25AianRPCSYFaHwReN3+i/jDBcbXH0iu5jbQ4QSxzOnZsn2ANOXgPPeehg1AAndrbKYfh2Qn6yu1Ls5J
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: maildev-basic-auth
    type: Opaque
