export const demandeStatusSejour = {
  BROUILLON: "BROUILLON",
  TRANSMISE: "TRANSMISE",
  EN_COURS: "EN COURS",
  A_MODIFIER: "A MODIFIER",
  ATTENTE_HEBERGEMENT: "EN ATTENTE VALIDATION HEBERGEMENT",
  ATTENTE_8_JOUR: "EN ATTENTE DECLARATION 8 JOURS",
  VALIDEE: "VALIDEE",
  REFUSEE: "REFUSEE",
};
