kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
data:
  API_INSEE_URL: "https://api.insee.fr"
  API_INSEE_URI: "/api-sirene/3.11"
  ANTIVIRUS_URL: "https://antivirus.fabrique.social.gouv.fr/vao/api/v1/scan"
  BACKEND_URL: "https://api-{{ .Values.global.host }}"
  FRONTEND_USAGERS_URL: "https://{{ .Values.global.host }}"
  FRONTEND_BO_URL: "https://bo-{{ .Values.global.host }}"
  SENDER_EMAIL: "nepasrepondre@vao.social.gouv.fr"
  SENTRY_DSN: "https://6b7cfbf810e478e2d66aa6700082476b@sentry2.fabrique.social.gouv.fr/16"
  SENTRY_ENABLED: "true"
  SENTRY_ENVIRONMENT: development
  TMP_DIRECTORY: "/tmp"
  BACKEND_CRON_REQUEST_ACCOUNT2M_NOTIFY_CRON: "*/15 * * * *"
  BACKEND_CRON_REQUEST_DS8J15J_NOTIFY_CRON: "*/15 * * * *"
  BACKEND_CRON_REQUEST_DS8J15J_DEADLINE_REMIND: "90"
  BACKEND_CRON_UPDATE_STATUT_DS_CRON: "*/15 * * * *"
  BACKEND_CRON_REQUEST_ACTIONS_BO_CRON: "0 9,12 * * 1-5"
