apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: frontend-secret
spec:
  encryptedData:
    SENTRY_AUTH_TOKEN: AgC9375+wcKRTtihuRR2e/Z533lVKm6Uck1od1kEQTDnaN9qKQI0RMFu84Iq4vKNs5hBnlvHf8UYn/dC3e6dYqIg00Z5YC/BVstAwYO4T+E9ETZiPCtDkP8p83E35ragNr3PpY8W9xTd1LVdVsHtWgoW4LG5CC4UMRqhHAbA/Hs/QuOn010uwoqCLik2ZHA8SFITI7p72H9loWxlVhj69AjR0aQXuZIfMIewb0X3IWQx10FVZP0z5W3sXEZnzsQYGmPC35oAxa8rf5ee4X78qLYPJ/4Tjm/atwkVftqDs6rkKbc4hEIcyPzD5yo2h94g9f2bC0QBz/br1gZhWRuNIgekOVBnOSNp3Es7zEGDw0PRobuXLf6CRrdiWPXWWt6J6UAi/OcdAtCEJnU0Q0P9hgYTYVfZURcseqfXfTEgvdVL4u6CA/zv2TJ3UBB3i+2efXRtJJ84n/BsuUI9ASN50Fa1rGOsRgfHu2RRm+tC/+MvqQJ84yxenmxv9FZLYQIGS4ZkuXvQ1NGJOxYDUqsGaZmgbvl5mjM2zjJ3Ta4ibEjcvT8u1EOs2JaYT1JnEOqy/SZXFI4duSGWlaRmWesdEjgEz/yuSy71d1ay4tB3cBnN9FlbYPKsYR7OGOiSr/dAEfVDZjSaIdS2afnh9FXFa8A7gj77/ZvTLWwiD80FMhf9nSWtbbUee61eE3g9nAplZr97Ls+SoO/Gi2nVurioI3CP4n6DY/I2ptKalKlo8NvnQze1eO8JPyDV8QsJKf/e90wgiUcgV6+0NenVb98fw0jJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: frontend-secret
    type: Opaque
