apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: maildev-basic-auth
spec:
  encryptedData:
    auth: AgChqa4ZXDkN8ZFUT8erfuQ84dUe6teyFSlXCJgCy9yYB2HGn60fUQ259FWXfBRxIgr99uukh/Yw4cwOHd+Jb9NtKSiPGH/Eb2CSGM3bKPEXYqW/eFGsxKBxN/plbYuwm7o9A0RkMN92XUlJhyvCOiw9K7TFKs45Rj+skXosBOGUue+Y9Az9aiV3u7qIpQuAfn4LEwb4Qi1xfR8s7Pj9Cmp8cokx2e9KJZKaew5DPvNlQBHX+mcl+eToSxZEkhMNRvS9dpzK+Kk3Fr35GFUOdq/kwrjtzw8kVwZK/zgKCxjxiz2KHGq3v12+OBjuAMMl4qgdtT8es26CXqntF42Z8h+r+mOJtAKQRa5bRaZrzLcejSndJDdZvjTpu/zipUQXRtWWkYDkhhsgZYkVYTl+KemCnivJppyfRNw1d+l0GORXPs1GNTWKU580VSU627R75gepeVFvmWfwxILF6L3k4JkcQu5nSjb5pqtXSyST0Pvp9LnHryrI37wge3FxQW+e5+3ODcfXWG4NNc/X9v1WXVeQK0gnq/zNe5szb3EzRPIa4ZdnLuoiaycnXUFH9MbJFwWqd/3Gc0IMHF5uD/4eKvUR9nuAE7AL+nziDuHRGLLmzF8Twq3cykxVg3mQqFv7vYiLzZAN4eZTruGC26buB95ys8S+bhDh3X+3H5Fp0h8dK0m00i8dxCYr4O7Tq71bbbqArZlDMhPNWAneOGbKke+94+0CArrkKP1tfC9sejXs/aabMwmkX4vaezwf3rKhEDjB0FmneoszT+TkR52Tojqu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: maildev-basic-auth
    type: Opaque
