export enum FILE_CATEGORY {
  PROCVERBAL = "AGR_PROCVERBAL",
  MOTIVATION = "AGR_MOTIVATION",
  IMMATRICUL = "AGR_IMMATRICUL",
  ASSURRESP = "AGR_ASSURRESP",
  ASSURRAPAT = "AGR_ASSURRAPAT",
  SEJOUR = "AGR_SEJOUR",
  ACCOMPRESP = "AGR_ACCOMPRESP",
  SUIVIMED = "AGR_SUIVIMED",
  BUDGET = "AGR_BUDGET",
  CHANGEEVOL = "AGR_CHANGEEVOL",
  BILANQUALIT = "AGR_BILANQUALIT",
  BILANFINANC = "AGR_BILANFINANC",
}
