projectName: vao
dependencies:
  fabrique:
    dependencies:
      contrib:
        patches:
          addJobsAffinityAndTolerations:
            enabled: false
          certs:
            options:
              internalHosts:
                - ".fabrique.social.gouv.fr"
                - ".social.gouv.fr"
