projectName: vao
dependencies:
  fabrique:
    extends:
      - name: ovh
    dependencies:
      contrib:
        patches:
          certs:
            options:
              internalHosts:
                - ".fabrique.social.gouv.fr"
                - ".social.gouv.fr"
