module.exports.statuts = {
  ATTENTE_8_JOUR: "EN ATTENTE DECLARATION 8 JOURS",
  A_MODIFIER: "A MODIFIER",
  BROUILLON: "BROUILLON",
  EN_COURS: "EN COURS",
  MAJ_POST_8J: "MAJ POST 8J",
  REFUSEE: "REFUSEE",
  TRANSMISE: "TRANSMISE",
  TRANSMISE_8J: "TRANSMISE 8J",
  VALIDEE: "VALIDEE",
};
