const dayjs = require("dayjs");
const dsStatuts = require("./ds-statuts");

module.exports.statuts = {
  BROUILLON: "BROUILLON",
  ENVOYE: "ENVOYE",
};

const Categorie = {
  FONCTIONNEMENT_ORGANISME: "FONCTIONNEMENT_ORGANISME",
  SANTE: "SANTE",
  SECURITE: "SECURITE",
  VICTIMES: "VICTIMES",
};

module.exports.Categorie = Categorie;

module.exports.Types = {
  [Categorie.VICTIMES]: {
    AUTRE: "AUTRE__VICTIMES",
    MALTRAITANCES_NON_PRECISEES: "MALTRAITANCES_NON_PRECISEES",
    NEGLIGENCE_GRAVE_OU_ERREURS_SUCCESSIVES:
      "NEGLIGENCE_GRAVE_OU_ERREURS_SUCCESSIVES",
    NON_RESPECT_PRESCRIPTION_MEDICALE: "NON_RESPECT_PRESCRIPTION_MEDICALE",
    PRIVATION_DE_DROIT: "PRIVATION_DE_DROIT",
    SUICIDE: "SUICIDE",
    TENTATIVE_DE_SUICIDE: "TENTATIVE_DE_SUICIDE",
    VIOLENCES_PHYSIQUES: "VIOLENCES_PHYSIQUES",
    VIOLENCES_PSYCHOLOGIQUES_ET_MORALES: "VIOLENCES_PSYCHOLOGIQUES_ET_MORALES",
    VIOLENCES_SEXUELLES: "VIOLENCES_SEXUELLES",
    VIOLS: "VIOLS",
  },
  [Categorie.SANTE]: {
    ACCIDENT_CORPOREL: "ACCIDENT_CORPOREL",
    AUTRE: "AUTRE__SANTE",
    EPIDEMIE: "EPIDEMIE",
  },
  [Categorie.SECURITE]: {
    ACTES_DE_MALVEILLANCE: "ACTES_DE_MALVEILLANCE",
    AUTRE: "AUTRE__SECURITE",
    DEPART_DE_FEU: "DEPART_DE_FEU",
    FUGUE: "FUGUE",
    INCENDIE: "INCENDIE",
    INONDATION: "INONDATION",
    INTOXICATION_ALIMENTAIRE: "INTOXICATION_ALIMENTAIRE",
    VOLS: "VOLS",
  },
  [Categorie.FONCTIONNEMENT_ORGANISME]: {
    AUTRE: "AUTRE__FONCTIONNEMENT_ORGANISME",
    CONFLITS_OU_MENACES_DE_CONFLITS_INTERNES:
      "CONFLITS_OU_MENACES_DE_CONFLITS_INTERNES",
    DEFAILLANCES_TECHNIQUES: "DEFAILLANCES_TECHNIQUES",
    DEFAILLANCE_DE_PERSONNELS: "DEFAILLANCE_DE_PERSONNELS",
    PROCEDURES_JUDICIAIRES_CONTRE_LE_PERSONNELS:
      "PROCEDURES_JUDICIAIRES_CONTRE_LE_PERSONNELS",
  },
};

module.exports.UpdateTypes = {
  DECLARATION_SEJOUR: "DECLARATION_SEJOUR",
  RENSEIGNEMENT_GENERAUX: "RENSEIGNEMENT_GENERAUX",
  TYPE_EVENEMENT: "TYPE_EVENEMENT",
};

module.exports.idDeclarationeligibleToEig = (d) =>
  d.dateDebut <= dayjs().format("YYYY-MM-DD") &&
  dayjs(d.dateFin).add(1, "week").format("YYYY-MM-DD") >=
    dayjs().format("YYYY-MM-DD") &&
  d.statut !== dsStatuts.statuts.BROUILLON;
