module.exports.status = {
  BLOCKED: "BLOCKED",
  NEED_EMAIL_VALIDATION: "NEED_EMAIL_VALIDATION",
  NEED_SIRET_VALIDATION: "NEED_SIRET_VALIDATION",
  TEMPORARY_BLOCKED: "TEMPORARY_BLOCKED",
  VALIDATED: "VALIDATED",
};

module.exports.roles = {
  EIG_ECRITURE: "Eig_Ecriture",
  EIG_LECTURE: "Eig_Lecture",
};
