{{- if .Values.externalApi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-api
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "external-api") | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    {{- include "vao.annotations" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMaps.externalApi.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}
