{{- if .Values.maildev.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "maildev") | nindent 4 }}
  annotations:
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vao.selectorLabels" (dict "context" . "component" "maildev") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vao.componentLabels" (dict "context" . "component" "maildev") | nindent 8 }}
    spec:
      containers:
        - name: maildev
          image: {{ .Values.maildev.image }}
          imagePullPolicy: IfNotPresent
          args:
            - --mail-directory
            - /home/node/maildev-data
          ports:
            - containerPort: 1080
              name: http
            - containerPort: 1025
              name: smtp
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            {{- toYaml .Values.maildev.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/node/maildev-data
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
