{{- if .Values.pgweb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "pgweb") | nindent 4 }}
  annotations:
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vao.selectorLabels" (dict "context" . "component" "pgweb") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vao.componentLabels" (dict "context" . "component" "pgweb") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: pgweb
          image: {{ .Values.pgweb.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: PGWEB_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.pgApp }}
                  key: uri
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.pgweb.resources | nindent 12 }}
{{- end }}
