{{- if and .Values.maildev.enabled .Values.maildev.ingress.enabled }}
{{- $host := .Values.maildev.host | default (printf "maildev-%s" (.Values.global.host | required "global.host must be set")) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maildev
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "maildev") | nindent 4 }}
  annotations:
    {{- with .Values.global.certManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
    {{- end }}
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: maildev
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ .Values.global.tlsSecretName | default "maildev-tls" }}
{{- end }}
