{{- if .Values.pgweb.enabled }}
{{- $host := .Values.pgweb.host | default (printf "pgweb-%s" (.Values.global.host | required "global.host must be set")) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgweb
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "pgweb") | nindent 4 }}
  annotations:
    {{- include "vao.annotations" . | nindent 4 }}
    {{- with .Values.pgweb.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: pgweb
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ .Values.global.tlsSecretName }}
{{- end }}
