{{- range $redirect := .Values.redirectIngresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-{{ $redirect.name }}
  labels:
    {{- include "vao.labels" $ | nindent 4 }}
  annotations:
    {{- include "vao.annotations" $ | nindent 4 }}
    nginx.ingress.kubernetes.io/permanent-redirect: {{ $redirect.target | quote }}
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  ingressClassName: {{ $.Values.global.ingressClassName }}
  {{- if $.Values.global.tlsSecretName }}
  tls:
    - hosts:
        - {{ $redirect.host }}
      secretName: {{ $.Values.global.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ $redirect.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-usagers
                port:
                  number: 80
{{- end }}
