apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "vao.labels" . | nindent 4 }}
    {{- with .Values.global.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    {{- include "vao.annotations" . | nindent 4 }}
