{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-ingress
  labels:
    {{- include "vao.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              network-policy/source: ingress-controller
    - from:
        - namespaceSelector:
            matchLabels:
              network-policy/source: monitoring
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
{{- if and .Values.pg.enabled .Values.networkPolicy.pgOperator.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pg-allow-operator
  labels:
    {{- include "vao.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: pg
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.cnpgOperatorNamespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
      ports:
        - port: 8000
        - port: 5432
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 8000
{{- end }}
