{{- $components := dict "backend" .Values.backend "external-api" .Values.externalApi "cron" .Values.cron "frontend-usagers" .Values.frontendUsagers "frontend-bo" .Values.frontendBo "migrate-s3" .Values.migrateS3 }}
{{- range $name, $config := $components }}
{{- if and $config.enabled $config.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    {{- include "vao.componentLabels" (dict "context" $ "component" $name) | nindent 4 }}
  annotations:
    {{- include "vao.annotations" $ | nindent 4 }}
spec:
  minAvailable: {{ $config.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "vao.selectorLabels" (dict "context" $ "component" $name) | nindent 6 }}
{{- end }}
{{- end }}
