{{- if .Values.maildev.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: maildev
  labels:
    {{- include "vao.componentLabels" (dict "context" . "component" "maildev") | nindent 4 }}
  annotations:
    {{- include "vao.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1080
      targetPort: http
      protocol: TCP
      name: http
    - port: 1025
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "vao.selectorLabels" (dict "context" . "component" "maildev") | nindent 4 }}
{{- end }}
