#!/usr/bin/env sh

corepack pnpm exec lint-staged

if sh -c ': >/dev/tty' >/dev/null 2>/dev/null; then exec </dev/tty; corepack pnpm exec node-talisman --githook pre-commit -i; else corepack pnpm exec node-talisman --githook pre-commit; fi
