log:
  level: debug
  format: text

storage:
  type: directory
  directory:
    path: "{{tmp}}"

cmd_default_params: &cmd_default_params
  driver:
    name: json
  validate: true
  timeout: 3600s
  expected_exit_code: -1
  executable: node

dump:
  transformation:
    - schema: doc 
      name: documents
      transformers: 
        - name: SetNull
          params:
            column: file

    - schema: back
      name: users
      transformers:
        - name: Cmd
          params:
            <<: *cmd_default_params
            args:
              - "./dist/back--users.js"
            columns:
              - name: mail
              - name: prenom
              - name: nom
              - name: pwd

    - schema: front
      name: users
      transformers:
        - name: Cmd
          params:
            <<: *cmd_default_params
            args:
              - "./dist/front--users.js"
            columns:
              - name: mail
              - name: prenom
              - name: nom
              - name: pwd
              - name: telephone

    - schema: front
      name: demande_sejour
      transformers:
        - name: Cmd
          params:
            <<: *cmd_default_params
            args:
              - "./dist/front--demande_sejour.js"
            columns:
              - name: libelle
              - name: responsable_sejour
