name: 👓 Review Auto
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feat/**"
      - "fix/**"
      - "chore/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  socialgouv:
    name: "🇫🇷 SocialGouv"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review-auto.yaml@v1
    secrets: inherit

  e2e:
    needs: socialgouv
    uses: ./.github/workflows/reusable-e2e.yaml
